# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "3.7"
# command to install dependencies
install:
before_script:
  - pip install tox-travis
{% if cookiecutter.coveralls -%}
  - pip install coveralls
{%- endif -%}
# command to run tests
script: tox
{% if cookiecutter.coveralls -%}
after_success: coveralls
{%- endif -%}

